import turtle
turtle.speed(1)
turtle.fillcolor("red")
turtle.begin_fill() 
turtle.forward(100) 
turtle.left(120)
turtle.forward(100) 
turtle.left(120)
turtle.forward(100) 
turtle.end_fill() 
turtle.done()